name: Manual Release Windows binary
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.4
      - name: Build release
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release -f .goreleaser.win.amd64.yaml --clean 
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: dist/*.zip

